{
 "title": "Benchmark",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-01-01T00:01:30.600Z" },
 "templating": {
  "list": [
   { "name": "filter", "label": "Filter" },
   {
    "name": "id_a",
    "label": "Benchmark id A",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "run_a",
    "label": "Run A",
    "query": {
     "query": "label_values(benchmark_mem_bytes{id=\"$id_b\"},run)"
    }
   },
   {
    "name": "id_b",
    "label": "Benchmark id B",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "run_b",
    "label": "Run B",
    "query": {
     "query": "label_values(benchmark_mem_bytes{id=\"$id_b\"},run)"
    }
   },
   { "name": "testtcp", "label": "TCP", "query": "dts,dtm,sts,stm" },
   { "name": "testudp", "label": "UDP", "query": "dus,dum,sus,sum" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1>Benchmark ${id_a}</h1></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<center><h1>Benchmark ${id_b}</h1></center>"
   }
  },
  { "title": "Result summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Stddev bandwidth by test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_a}\"}) by (test)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stddev bandwidth by test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_b}\"}) by (test)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Bandwidth by test",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_a}\",run=~\"${run_a}\"} ) by (test)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "Average Bandwidth by test",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_b}\",run=~\"${run_b}\"} ) by (test)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "Bandwidth by test with run details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_a}\",run=~\"${run_a}\"} ) by (test,run)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "Bandwidth by test with run details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_b}\",run=~\"${run_b}\"} ) by (test,run)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "IDLE - System metrics when there is no traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "[IDLE] - Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"client\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[IDLE] - Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"client\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[IDLE] - CPU Client",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"client\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[IDLE] - CPU Client",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"client\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[IDLE] - CPU Server",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"server\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[IDLE] - CPU Server",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"server\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[IDLE] - Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    },
    {
     "title": "[IDLE] - Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    }
   ]
  },
  { "title": "Tests TCP - $testtcp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "testtcp" },
  {
   "title": "[$testtcp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_a\",test=~\"$testtcp\",run=~\"$run_a\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_retransmits_count{id=~\"$id_a\",test=~\"$testtcp\",run=~\"$run_a\"})",
     "legendFormat": "retransmits"
    }
   ]
  },
  {
   "title": "[$testtcp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_b\",test=~\"$testtcp\",run=~\"$run_b\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_retransmits_count{id=~\"$id_b\",test=~\"$testtcp\",run=~\"$run_b\"})",
     "legendFormat": "retransmits"
    }
   ]
  },
  {
   "title": "[$testtcp] - Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$testtcp] - Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$testtcp] - CPU Client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testtcp] - CPU Client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testtcp] - CPU Server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testtcp] - CPU Server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testtcp] - Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$testtcp] - Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_a}\",instance=~\"$testtcp\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  { "title": "Tests UDP - $testudp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }, "repeat": "testudp" },
  {
   "title": "[$testudp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})",
     "legendFormat": "Jitter"
    },
    {
     "expr": "#avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})\navg(benchmark_iperf_lost_percent{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "[$testudp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "Jitter"
    },
    {
     "expr": "avg(benchmark_iperf_lost_percent{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "[$testudp] - Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$testudp] - Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$testudp] - CPU Client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testudp] - CPU Client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testudp] - CPU Server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testudp] - CPU Server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$testudp] - Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$testudp] - Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  { "title": "Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 104 },
   "options": {
    "content": "# Kubernetes CNI benchmark by infraBuilder and BlackSwift\n\nTwitter : [@infrabuilder](https://twitter.com/infrabuilder) - [@BlackSwiftFR](https://twitter.com/blackswiftfr)\n\nWeb : [infraBuilder.com](https://infrabuilder.com) - [BlackSwift.fr](https://www.blackswift.fr)"
   }
  }
 ]
}