{
 "title": "Benchmark Results",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-01-01T00:01:30.600Z" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Benchmarks",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "test",
    "label": "Tests",
    "query": "dts, dtm, dus, dum, sts, stm, sus, sum"
   }
  ]
 },
 "panels": [
  {
   "title": "Benchmark result for test $test",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Maximum bandwidth result other all runs within a benchmark for a specific test\nmax(\n    benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",id!~\"(baremetal|flannel)\",test=\"$test\"}\n) by (id) @ start()",
     "legendFormat": "bw"
    },
    {
     "expr": "# Maximum bandwidth result other all runs within a benchmark for a specific test\nmax(\n    benchmark_iperf_bandwidth_bits_per_second{id=~\"(baremetal|flannel)\",test=\"$test\"}\n) by (id) @ start()",
     "legendFormat": "bw"
    }
   ]
  },
  {
   "title": "Ressources efficiency per CNI for test \"$test\"",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(# CPU\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n) * 1000 # Converting CPU in mCPU\n\n/\n\n(# BW in Gbit/s\n    # Maximum bandwidth result other all runs within a benchmark for a specific test\n    max(\n        benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n    ) by (id) @ start() \n    / 1G\n)\n\n#or label_set(0,\"id\",\"origin\")\n#or label_set(0,\"id\",\"maxX\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\navg_over_time(statexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n) by (id) \n-\nmax(avg_over_time(statexec_memory_used_bytes{id=\"baremetal\",instance=~\"$test\"}[40s]) @ ( end() - 30 ))\n\n\n#or label_set(0,\"id\",\"origin\")\n#or label_set(1.5Gi,\"id\",\"maxX\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Benchmark result for test $test",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "# Maximum bandwidth result other all runs within a benchmark for a specific test\nmax(\n    benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n) by (id) @ start()",
     "legendFormat": "bw"
    },
    {
     "expr": "(# CPU\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n) * 1000 # Converting CPU in mCPU\n\n/\n\n(# BW in Gbit/s\n    # Maximum bandwidth result other all runs within a benchmark for a specific test\n    max(\n        benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n    ) by (id) @ start() \n    / 1G\n)",
     "legendFormat": "cpueff"
    },
    {
     "expr": "max(\navg_over_time(statexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n) by (id)\n-\nmax(\navg_over_time(statexec_memory_used_bytes{id=\"baremetal\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n)\n",
     "legendFormat": "memover"
    }
   ]
  },
  {
   "title": "Ressources efficiency per CNI for test \"$test\"",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(# CPU\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n) * 1000 # Converting CPU in mCPU\n\n/\n\n(# BW in Gbit/s\n    # Maximum bandwidth result other all runs within a benchmark for a specific test\n    max(\n        benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n    ) by (id) @ start() \n    / 1G\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\navg_over_time(statexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n) by (id) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Summary check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "(# CPU Detail\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[1s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n)",
     "legendFormat": "{{id}} detail"
    },
    {
     "expr": "\n(# CPU summary\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n)",
     "legendFormat": "{{id}} summary"
    }
   ]
  },
  {
   "title": "Informations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
     "options": {
      "content": "Test naming : `[ds][tu][sm]`\n- `[ds]` : Direct mode (ip to ip) or via Service (pod to service)\n- `[tu]` : Tcp or Udp protocol\n- `[sm]` : Single stream or Multi streams (8 threads iperf3)\n\nExemples: `dus` stands for Direct Udp Singlestream, `stm` is Service Tcp Multistream\n\n---\n\nRepo: https://github.com/InfraBuilder/benchmark-k8s-cni-2024-01/\n\nTwitter : [@infrabuilder](https://twitter.com/infrabuilder) - [@BlackSwiftFR](https://twitter.com/blackswiftfr)\n\nWeb : [infraBuilder.com](https://infrabuilder.com) - [BlackSwift.fr](https://www.blackswift.fr)"
     }
    }
   ]
  }
 ]
}